import { Link } from 'lucide-react'
import { register } from 'module'
import type { Metadata } from 'next'
import { Inter, Oswald } from 'next/font/google'
import { Input } from 'postcss'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '/me-quiz',
  description: 'Generated by create next app',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <main className="min-h-screen grid lg:grid-cols-[3fr_2fr] grid-cols-1">
      {children}

      <div className="h-screen hidden lg:block">
        <img
          className="w-full h-full object-cover"
          src="https://images.pexels.com/photos/8609315/pexels-photo-8609315.jpeg?auto=compress&cs=tinysrgb&w=1600"
          alt=""
        />
      </div>
    </main>
  )
}
